server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ajxalianxi?serverTimezone=UTC
    username: root
    password: root
  application:
    name: serviceprovider
mybatis:
  type-aliases-package: com.liujijing.entity
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
