server:
  port: 80
spring:
  application:
    name: service_consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000